apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-holtyvru
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-holtyvru:88edeb8685133e93f7294de5a1900938c97f937c@sha256:fb84e40429c6c4cce89722ac0127d13d23ed6488abcfdb4ce577cb63d548c6cc
          name: container-image
